/*
 * ultrasonic.c
 *
 *  Created on: 12 Oct 2024
 *      Author: farah
 */
#include"ultrasonic.h"
#include"icu.h"
#include"gpio.h"
#include <util/delay.h> /* For the delay functions */

uint8 g_edgeCount = 0;
uint16 g_timeHigh = 0;   /*echo high time*/

ICU_ConfigType ICU_Configurations = {F_CPU_8,RAISING};
/************************************************************************************/

void Ultrasonic_init(void)
{
	/*Initialise the ICU driver*/
	ICU_init(&ICU_Configurations);
	/*Set up the ICU callback function */
	ICU_setCallBack(Ultrasonic_edgeProcessing);
	/*Set the direction for the trigger pin as output*/
	GPIO_setupPinDirection(Trigger_PORT_ID , Trigger_PIN_ID , PIN_OUTPUT);
}

/**************************************************************************************/
void Ultrasonic_Trigger(void)
{
	/*Send the trigger pulse to the ultrasonic sensor.*/
	GPIO_writePin( Trigger_PORT_ID    ,  Trigger_PIN_ID   , LOGIC_HIGH);
    _delay_us(20);
    GPIO_writePin( Trigger_PORT_ID    ,  Trigger_PIN_ID   , LOGIC_LOW);
}
/***************************************************************************************/
uint16 Ultrasonic_readDistance(void)
{
	/* return the measured distance in centimetres*/
    return ((g_timeHigh/117.6)+1);
}
/**************************************************************************************/
/*callback function called by the ICU driver.
* It calculates the high time (pulse time) generated by
*the ultrasonic sensor.*/

void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		ICU_clearTimerValue();
		/* Detect falling edge */
		ICU_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_timeHigh = ICU_getInputCaptureValue();
		/* Clear the timer counter register to start measurements again */
		ICU_clearTimerValue();
		/* Detect rising edge */
		ICU_setEdgeDetectionType(RAISING);

		g_edgeCount=0;
	}
}
/*************************************************************************************/
